### ISSUE TITLE
Failed import "python_2_unicode_compatible".

### ISSUE THREAD

**Issue by MeanEYE** [base4sistemas/pyescpos#22]
When starting a program that relies on this project the following exception is raised:
```
Traceback (most recent call last):
  File "./label_maker.py", line 14, in <module>
    from escpos import BluetoothConnection
  File "/home/meaneye/Development/Workspace/Python/LabelMaker/lib/escpos/escpos/__init__.py", line 31, in <module>
    from .conn import *  # noqa: E402,F401,F403
  File "/home/meaneye/Development/Workspace/Python/LabelMaker/lib/escpos/escpos/conn/__init__.py", line 27, in <module>
    from .bt import BluetoothConnection
  File "/home/meaneye/Development/Workspace/Python/LabelMaker/lib/escpos/escpos/conn/bt.py", line 27, in <module>
    from future.utils import python_2_unicode_compatible
ModuleNotFoundError: No module named 'future'
```
Python 3.8.6

**Comment by danielgoncalves** [comment]
Thanks for the report. Fixed in [this commit](https://github.com/base4sistemas/pyescpos/commit/58ebc1b544458803c4235f3fa80e8fa376b18ec2)
